PLATUI-2034: Page Capture Extension MVP
hmrc/hmrc-page-capture pull request #1
Opened 2022-12-15 15:02 UTC by tmc-ee

First iteration of page capture extension.

The first commit demonstrates capturing pages in a single file in MHTML format using [pageCapture](https://developer.chrome.com/docs/extensions/reference/pageCapture/) API.

The second commit demonstrates capturing pages in separate files in HTML and CSS format by interrogating the DOM on page load.

We (@testleads) settled on the second solution as it allows more flexibility down the line when we start to assess pages in accessibility tools such as [axe](https://github.com/dequelabs/axe-core) and [v.Nu](https://github.com/validator/validator).

The source code captured in the second solution also represents what is served by the browser more closely (i.e. CSS styles and scripts are not inlined all over the place).

2022-12-16 15:28 UTC, kyle-bowden commented on src/background.ts
> +    filename: `${timestamp}/${filename}`,
Could we download all pages to a specific folder in the download folder like `accessibility-pages` for example, it will be nicer for the user to have a folder where all the timestamped folders reside. My thinking is that because its the downloads folder the user could have other files folders in there, which could make it confusing to find etc

```
function downloadPage(timestamp: number, filename: string, url: string) {
  chrome.downloads.download({
    url,
    filename: `accessibility-pages/${timestamp}/${filename}`,
  });
}
```

2022-12-16 15:39 UTC, kyle-bowden commented on src/background.ts
> +chrome.runtime.onMessage.addListener((request, sender, response) => {
Could we move out the event listener logic into a named method for easier readability

```
import MessageSender = chrome.runtime.MessageSender;

function onPageLoaded(request: any, sender: MessageSender) {
  const pageUrl = sender.url;
  const page = request.payload;
  const timestamp = Date.now();

  savePageUrl(pageUrl);
  getPageData(timestamp, page, pageUrl);

  page.forEach((asset: string) => {
    const filename = JSON.parse(asset).filename;
    const url = JSON.parse(asset).url;

    downloadPage(timestamp, filename, url);
  });
}

chrome.runtime.onMessage.addListener(onPageLoaded);
```

2022-12-16 15:45 UTC, kyle-bowden commented on .gitignore
> -/.idea
Can we include all the intellij specific files, folders please

.idea
target
/*.iml
/out

2022-12-16 15:54 UTC, kyle-bowden requested changes
I have spotted a few minor things that can be tweaked.

2022-12-19 10:47 UTC, tmc-ee commented on src/background.ts
> +    filename: `${timestamp}/${filename}`,
Done. I've named the directory `hmrc-page-capture` to keep it generic (i.e. not tied exclusively to accessibility).

2022-12-19 10:47 UTC, tmc-ee commented on src/background.ts
> +chrome.runtime.onMessage.addListener((request, sender, response) => {
Done. Thanks for this :+1:

2022-12-19 10:48 UTC, tmc-ee commented on .gitignore
> -/.idea
Done. Reinstated the original `.gitignore` file.

2022-12-19 10:51 UTC, kyle-bowden approved these changes

2022-12-19 11:07 UTC, vivrichards600 approved these changes
Changes look good.

2022-12-19 11:08 UTC, merged